Add user creation and editing for admins
openmultiplechoice/openmultiplechoice pull request #1019
Opened 2024-10-23 21:02 UTC by levinuss

This commit enables admins to create new users and edit existing ones through the user management interface.

2024-10-30 14:37 UTC, schu requested changes
Looks good to me UI-wise. A couple of comments inline. Unless there's a good reason for why admins should be able to initiate a password reset, I would prefer if only the user personally can inititiate a reset.

2024-10-30 16:38 UTC, schu commented on resources/views/user.blade.php
> +                        <label for="email_verified_at" class="form-label">E-Mail verified</label>
`E-Mail verified` -> `Email verified`

2024-10-30 17:30 UTC, levinuss commented on resources/views/user.blade.php
> +</form>
Form nesting is not allowed, so we would not be able to have the password reset form in this place. Or am I missing something?

2024-10-31 10:06 UTC, schu requested changes
Late second thought: let's not include the delete part for now, I think that requires more thought (what can and should be deleted, what not – for example, what should happen with _public-rw-listed_ decks) and work (for example, it doesn't work as-is if the user has created sessions due to a foreign key violation).

Also, two style nits inline.

2024-10-31 10:07 UTC, schu commented on resources/views/user.blade.php
> +</form>
OK, I didn't remember that.

2024-11-05 09:00 UTC, merged

2024-11-05 09:01 UTC, schu commented
Thanks!

Two thoughts for a later update:

- I would prefer if we restrict edits for users loaded from Keycloak (SSO), i.e. don't allow name and email edits (Keycloak is source of truth) and disable setting a password (users should not be able to bypass the SSO system)
- Creating a new user with an invalid email address results in the user being created and a `UnexpectedResponseException` being returned (`sendResetLink` fails)