Limit metadata edits of `public-rw-listed` decks
openmultiplechoice/openmultiplechoice pull request #1024
Opened 2024-11-01 23:06 UTC by levinuss

This limits the metadata edits of `public-rw-listed` decks (name, exam date, module, description) to admins and moderators. Also enabled the un-listing of `public-rw-listed` decks by admins or moderators.
Closes #977

2024-11-01 23:08 UTC, levinuss commented
@schu
Unlisting of `public-rw-listed` decks was disabled for all users before, I thought it may be useful to enable this for admins and moderators (while I'm at it). Do you agree?
You did not mention the description field in the issue. Do you think that should be editable by all users?

2024-11-05 09:15 UTC, schu requested changes

2024-11-05 09:15 UTC, schu commented on resources/views/deck-editor.blade.php
> +                    <input type="text" id="description" name="description" class="form-control" disabled value="{{ old('description', $deck->description) }}">
Since the description contains HTML code, let's render it (identical to the [deck page](https://github.com/openmultiplechoice/openmultiplechoice/blob/7ffece4e2b97757e9108b7019b58556317dbb814/resources/views/deck.blade.php#L77-L79)) to make it readable.

2024-11-05 09:19 UTC, schu commented
> Unlisting of `public-rw-listed` decks was disabled for all users before, I thought it may be useful to enable this for admins and moderators (while I'm at it). Do you agree?

OK.

> You did not mention the description field in the issue. Do you think that should be editable by all users?

I'm OK with limiting description edits for now (and changing it later, if necessary).

2024-11-05 10:23 UTC, levinuss commented
Thanks, requested change done.
I also thought about disabling the edit page completely for `public-rw-listed` decks for normal users (because all fields are disabled anyway) and hiding the 'Settings' button. But I think it might be nice to have that page for a overview.

2024-11-05 14:02 UTC, schu requested changes

2024-11-05 14:08 UTC, schu commented
> I also thought about disabling the edit page completely for public-rw-listed decks for normal users (...) and hiding the 'Settings' button. But I think it might be nice to have that page for a overview.

I also think the settings page should remain accessible to not be confusing ("some decks have settings, some don't?").

2024-11-05 15:29 UTC, levinuss commented on resources/views/deck-editor.blade.php
> +                    You cannot edit this decks metadata because it is <i>public-rw-listed</i>.<br>
Without the 's' it also would not be a correct english sentence, right? Edited it, should now be fine.

2024-11-05 15:45 UTC, schu commented on resources/views/deck-editor.blade.php
> +                    You cannot edit this decks metadata because it is <i>public-rw-listed</i>.<br>
Right, should have been `deck's` I think. Anyway, going with the current version.

2024-11-05 15:45 UTC, merged