NewSessionDecksView: let users browse their own and all public decks
openmultiplechoice/openmultiplechoice pull request #1030
Opened 2024-11-16 17:22 UTC by schu

First step towards [Refactor new session page #1027](https://github.com/openmultiplechoice/openmultiplechoice/issues/1027).

2024-11-17 19:01 UTC, levinuss requested changes
Works & looks nice (other than the comments)

2024-11-24 09:32 UTC, schu commented on resources/js/NewSessionDecksView.svelte
> +                <option value="public-rw-listed" selected={deckKind === 'public-rw-listed'}>Public decks</option>
I changed the wording to

```
Main decks
Your decks
User decks
```

for the time being. If OK for you, I would like to go with this variant and adjust the wording later, if necessary.

2024-11-24 09:37 UTC, schu commented on app/Http/Controllers/SessionController.php
> +            Auth::user()->settings->last_module_id = $validated['module'];
If a module is set in the URL paramenters (`?module=...`), we want it to take precedence over what is stored as `last_module_id`, otherwise links wouldn't work as expected. For example, if I send you `http://127.0.0.1:8000/sessions/create?kind=public&module=1&page=1`, you should see the first page of public decks in module 1, even if your previous `last_module_id` was `2`.

I updated the comment to hopefully make it more clear.

2024-11-24 09:39 UTC, schu commented on app/Http/Controllers/Api/DeckController.php
> +                    ->where('access', '!=', 'private')
Thanks for catching this, I updated the query to not only take public decks but also the decks owned by the user. Please take another look.

2024-11-24 12:15 UTC, levinuss approved these changes
Thanks for the changes!
Did not find anything else, looks good

2024-11-25 17:40 UTC, merged