Add voting on comments
openmultiplechoice/openmultiplechoice pull request #766
Opened 2024-03-10 13:09 UTC by levinuss

Adds voting on question comments with an up- or a downvote. Users can only vote once and can see the number of total votes for each type and their own vote on each comment.

closes #758

2024-03-12 19:00 UTC, schu requested changes

2024-03-12 20:30 UTC, levinuss commented on resources/js/MessageView.svelte
> +        // Get the message the vote was made/changed/deleted on to update the number of votes and the users vote
You mean by manipulating the `message.thumb` array manually in the `.then` handlers (by e.g. adding one upvote after the user upvoted something) without querying the actual data from the DB?

2024-03-12 20:33 UTC, levinuss commented on app/Http/Controllers/Api/QuestionMessageController.php
> +        $messages = $question->messages()->with('thumbs')->get();
Yes. Without this change, Eloquent will lazy-load the `thumbs` relation to each message inside of the `thumbsAnonymized` function (which will result in an additional database query for each message that is being loaded).

2024-03-12 20:59 UTC, schu commented on app/Http/Controllers/Api/QuestionMessageController.php
> +        $messages = $question->messages()->with('thumbs')->get();
👍

2024-03-12 21:00 UTC, schu commented on resources/js/MessageView.svelte
> +        // Get the message the vote was made/changed/deleted on to update the number of votes and the users vote
Yes.

2024-03-12 21:54 UTC, levinuss commented on resources/js/MessageView.svelte
> +        // Get the message the vote was made/changed/deleted on to update the number of votes and the users vote
Changed it like this. Had to use the weird `message = message;` statement because the reactive variables wouldn't update otherwise.

2024-03-13 18:14 UTC, schu commented on resources/js/MessageView.svelte
> +        // Get the message the vote was made/changed/deleted on to update the number of votes and the users vote
Yes, that seems a bit odd at first but is expected (https://learn.svelte.dev/tutorial/updating-arrays-and-objects).

2024-03-14 18:51 UTC, schu requested changes

2024-03-14 18:51 UTC, schu commented on app/Http/Controllers/Api/MessageThumbController.php
> +     * Store a new thumb for the specified message
Nit: your other comments end with a `.`, here it's missing.

2024-03-14 18:51 UTC, schu commented on app/Http/Controllers/Api/QuestionMessageController.php
> +    public function show(Request $request, Question $question, Message $message)
As far as I see, this method is from a previous iteration of the PR and not actually needed. Let's remove it then.

2024-03-14 18:53 UTC, schu commented
Currently, the PR cannot be merged due to conflicts, please rebase before re-building the JavaScript components.

2024-03-17 18:29 UTC, levinuss commented
> Currently, the PR cannot be merged due to conflicts, please rebase before re-building the JavaScript components.

Should be resolved now (even though I still don't unterstand why JS components that I did not touch were rebuild as well)

2024-03-19 20:18 UTC, schu requested changes

2024-03-19 20:18 UTC, schu commented on resources/js/MessageView.svelte
> +                    // add a new vote to the thumbs array in the local copy
Nit: `add the new ...`

2024-03-19 20:18 UTC, schu commented on app/Http/Controllers/Api/MessageThumbController.php
> +            abort(400, 'You are not allowed to update this thumb.');
This should be 403 forbidden. Same below in the `destroy` method.

2024-03-20 19:55 UTC, levinuss commented on resources/js/Messages.svelte
> +        messages = messages.map(obj => {
Looks better

2024-03-20 21:04 UTC, merged