Make deck's `access` attribute editable and set default to 'private'
openmultiplechoice/openmultiplechoice pull request #776
Opened 2024-03-14 19:10 UTC by schu

So far the `access` attribute was mostly a stub and not yet editable by the user. Add a select element to the deck form to make it editable. Also change the default `access` to private so that user collections are private by default. Note that we don't plan to have private questions currently, i.e. only the collection of questions is private but not the contents of the individual questions in the deck.

Admins continue to be able to edit all decks, but we should add a warning to decks where the admin user isn't the owner to avoid accidental edits. (Will follow in a later commit.)

Also, add a few comments and extra lines to make the code more readable.

2024-03-17 19:31 UTC, levinuss requested changes
Looks good other than the 2 issues with deck editing I found. Can't think of any other ways to access private decks or change the access level.

2024-03-17 19:31 UTC, levinuss commented on resources/views/deck-editor.blade.php
> +                    <select id="access" name="access" class="form-select" disabled>
Because the `select` is disabled here, the `access` parameter will be empty in the POST which will result in a query like this:
```
UPDATE "decks"
SET "access" =,
  "updated_at" = '2024-03-17 19:11:10'
WHERE "id" = 3
```
which will set the corresponding deck to the default access level (= private).
At the same time, a request with `public-rw-listed` as access level will fail with 403, so there should probably be an additional backend check for this case (updating other fields of a listed deck).

2024-03-17 19:31 UTC, levinuss commented on app/Http/Controllers/Api/DeckController.php
> +        $deck->access = $request->access;
Changing of deck access should be restricted (to admins?) for decks with the `public-rw-listed` access level to prevent users from de-listing decks (as the frontend check / disabled form suggests).
Same for the frontend controller.

2024-03-17 19:31 UTC, levinuss commented on app/Http/Controllers/DeckController.php
> +        $deck->access = $request->access;
Changing of deck access should be restricted (to admins?) for decks with the `public-rw-listed` access level (see above).

2024-03-22 11:46 UTC, schu commented on resources/views/deck-editor.blade.php
> +                    <select id="access" name="access" class="form-select" disabled>
Thanks, somehow I missed this in my testing.

`disabled` elements are not sent on submit, hence the problem. We could use `readonly` instead, but `readonly` elements can be confusing as it's not immediately obvious to the user that the field cannot be changed. Instead, I kept the `disabled` select and added a second hidden input for the value.

2024-03-22 11:48 UTC, schu commented on app/Http/Controllers/Api/DeckController.php
> +        $deck->access = $request->access;
Above we check if access is set to `public-rw-listed`, but that's not obvious on the diff here on GitHub. Or am I missing something?

Currently, the only way to switch to `public-rw-listed` should be the submission flow, even for admins.

Same for you comment below, I think.

2024-03-24 13:19 UTC, levinuss commented on resources/views/deck-editor.blade.php
> +                    <select id="access" name="access" class="form-select" disabled>
Looks good now

2024-03-28 12:09 UTC, levinuss approved these changes

2024-03-30 09:33 UTC, merged