Add basic sign-up and password reset flows
openmultiplechoice/openmultiplechoice pull request #808
Opened 2024-04-15 14:44 UTC by levinuss

see commit messages

2024-04-19 09:25 UTC, schu requested changes

2024-04-19 09:25 UTC, schu commented on resources/views/registration-token.blade.php
> +@section('content')
So far we have the following structure and alignment in most templates:

```
@section('content')

<div ...
    ...
</div>

@endsection
```

i.e. start of section - empty line - start of HTML without indendation for the top element - content - empty line -end of section.

The added/updated templates here currently use a mix of multiple variants. I would prefer it we try to keep this consistent.

2024-04-19 09:25 UTC, schu commented on resources/views/registration-token.blade.php
> +                    @error('count')
Above it's

```
@error...
    something with indent
@enderror
```

below it's a mix, here it's without indent. I think we tend to have with indent for Blade statements, but I didn't check. I think we should set on a style and try to be consistent.

2024-04-19 09:25 UTC, schu commented on routes/web.php
> +    // Verify email manually since EmailVerificationRequest does only work when the user is logged in
As far as I understand, you are referring to the fact that Laravel's `EmailVerificationRequest` flow expects the user to be logged in already (despite their email not being verified yet). Maybe something like the following comment would be clearer:

```
    // You might wonder why we implement our own email verification handler
    // instead of using the approach described in Laravel's documentation:
    // https://laravel.com/docs/11.x/verification#the-email-verification-handler
    // 
    // The reason is that the documented approach expects the user to be
    // logged in when verifying their email. We prefer to only allow users
    // to log in if and only if their email is verified already to avoid
    // the state "logged in but actually not verified yet".
```

2024-04-19 09:25 UTC, schu commented on routes/web.php
> +        return redirect()->route('login')->with('msg-success', 'Email '.$user->email.' verified');
Maybe we can put the email address in quotes (`"foo@example.com"`) to make it more readable.

2024-04-19 09:25 UTC, schu commented on routes/web.php
> +    return back()->with('msg-success', 'If there is an account with the email address you entered, we have sent a verification link to it.');
I think it would be helpful to echo the email address in the success message to allow users recognizing a typo after they sent the form. Also, I think it's enough to say

```
We have sent a verification email to "foo@example.com".
```

For valid users and requests that's what we did, and we don't really care about invalid or "malicious" requests.

2024-04-19 09:25 UTC, schu commented on routes/web.php
> +    return back()->with('msg-success', 'If the email address exists in our system, a password reset link has been sent.');
As above, maybe something like

```
We have sent a reset link to "foo@example.com".
```

2024-04-19 09:27 UTC, schu commented
A few things that we have to look into later (not as part of this PR):

* With sign-up mode `manual`, admins need to actively enable user accounts before the user can log in. But there's no good way for admins to a) see if there are new users to be enabled and b) distinguish between users who are disabled because they require "admin approval" and users who are disabled because their account was deliberately disabled..
* With sign-up mode `manual`, users sign up, they confirm their email and get to see a success message ("Email verified ..."). Then they try to log in and are presented with the message "Your account is disabled and/or has no verified email address." This is a bit confusing and probably not clear to all users. I don't have a good idea yet on how to solve this differently.
* The admin user list (`/admin/users`) shows SSO users with an unverified email address icon. To admins it's not clear if this is a SSO based user (email verification is not OMC's responsibility) or a user that used OMC's sign-up (where the email address should be verified eventually).

2024-04-20 12:35 UTC, levinuss commented on resources/views/login.blade.php
> +            <div class="row justify-content-between">
If I understand correctly, if I use block buttons, "Sign up"  cannot have its own column?
What do you think of my new proposal in the lastest push?

2024-04-20 12:36 UTC, levinuss commented on app/Models/User.php
> +class User extends Authenticatable implements MustVerifyEmail, CanResetPassword
True. Should we just leave it like this and mention it in a Changelog?

2024-04-20 12:37 UTC, levinuss commented on app/Http/Controllers/RegistrationController.php
> +                Rule::when($allowed_domain, 'ends_with:'.$allowed_domain)],
Yes, its better to have this explicit

2024-04-20 12:38 UTC, levinuss commented on config/auth.php
> +            'table' => 'password_resets',
Yes, it seems the table name changed during a Laravel version change because the table created with our migrations did not match the default table name. So I had the option to either add a new migration to change / recreate the table (name) or to change this config option.

2024-04-20 12:55 UTC, levinuss commented on resources/views/admin-settings-signup.blade.php
> +                    <div class="invalid-feedback">{{ $message }}</div>
Fixed

2024-04-20 13:01 UTC, levinuss commented on routes/web.php
> +    // Verify email manually since EmailVerificationRequest does only work when the user is logged in
Correct, thanks for writing this out

2024-04-27 10:26 UTC, schu requested changes

2024-04-27 10:26 UTC, schu commented on resources/views/registration-token.blade.php
> +    <form method="post">
Please put the form into a row as well (with a single column in this case).

Also, the form elements (`div`s) currently don't have a bottom margin, so when stacked there are no "clean margins":

![image](https://github.com/openmultiplechoice/openmultiplechoice/assets/366468/a60618d8-e085-4389-a092-ecaa5cf290d1)

In most other forms we use `mb-3` I think, see for example the login form.

2024-04-27 10:26 UTC, schu commented on app/Models/User.php
> +class User extends Authenticatable implements MustVerifyEmail, CanResetPassword
Yes.

2024-04-27 10:26 UTC, schu commented on config/auth.php
> +            'table' => 'password_resets',
Ack.

2024-04-27 10:26 UTC, schu commented on resources/views/login.blade.php
> +            <div class="row justify-content-between">
The updated version looks and stacks better, further changes can follow in a later PR, if necessary.

2024-04-28 15:48 UTC, levinuss commented on database/migrations/2024_04_02_225223_create_registration_tokens_table.php
> +            $table->timestamp('expires_at');
Good catch, is this confirmed to work with `->useCurrent()` on MySQL?

2024-04-30 17:04 UTC, schu requested changes
Two more small issues.

I'm planning on merging after those are fixed, everything else we can tackle iteratively.

2024-04-30 17:05 UTC, schu commented on database/migrations/2024_04_02_225223_create_registration_tokens_table.php
> +            $table->timestamp('expires_at');
Yes, I only noticed it because my dev environment is using MySQL currently.

2024-04-30 17:40 UTC, levinuss commented on resources/views/login.blade.php
> +                    <button type="button" href="{{ route('signup') }}" class="btn btn-link">Sign up</button>
Don't know how that slipped through, thanks!

2024-04-30 17:42 UTC, levinuss commented
> Two more small issues.
> 
> I'm planning on merging after those are fixed, everything else we can tackle iteratively.

Done

2024-04-30 18:31 UTC, merged

2024-04-30 18:31 UTC, schu commented
Thank you!