[WIP] Add support for cases
openmultiplechoice/openmultiplechoice pull request #914
Opened 2024-07-06 20:04 UTC by schu

2024-07-10 13:34 UTC, levinuss requested changes
Other than these things, this looks nice I think!

2024-07-10 13:34 UTC, levinuss commented on resources/js/QuestionForm.svelte
> +                <div class="alert alert-light" role="alert">
Missing margin on this alert element, it will be right next to the "Close" button in the SessionView if the editor is enabled and the question does not have a case assigned. Add `mt-3` (like the CaseForm has)?

2024-07-10 13:34 UTC, levinuss commented on resources/js/QuestionForm.svelte
> +    export let cases;
The cases variable is not bound to QuestionForm in SessionQuestionView (line 95) which results in no cases shown in the editor even though there may be some for the deck.

2024-07-10 13:34 UTC, levinuss commented on resources/js/QuestionForm.svelte
> +                                <select id="case" bind:value={selectedCase} on:change={handleQuestionCaseChange}>
Is there a reason you did not use the [bootstrap select](https://getbootstrap.com/docs/5.3/forms/select/) (e.g. add the `form-select` class)?
Same for the question type change select.

2024-07-10 13:34 UTC, levinuss commented on resources/js/CaseForm.svelte
> +<form action="#" class="mt-3 mb-1 p-3 bg-light-subtle rounded">
Is there a reason for `p-3` here? Makes the form look a bit misplaced in my opinion (but could also be used to display the superior position of the case compared to the question.

2024-07-21 18:22 UTC, schu commented
The first iteration felt like a wrong shortcut, I've reworked most of it. Please take another look and give it a try.

2024-07-21 18:23 UTC, schu commented on resources/js/QuestionForm.svelte
> +    export let cases;
Thanks, this should be gone now.

2024-07-21 18:23 UTC, schu commented on resources/js/QuestionForm.svelte
> +                                <select id="case" bind:value={selectedCase} on:change={handleQuestionCaseChange}>
That was an oversight, fixed not, thanks for catching!

2024-07-21 18:25 UTC, schu commented on resources/js/CaseForm.svelte
> +<form action="#" class="mt-3 mb-1 p-3 bg-light-subtle rounded">
This particular `p-3` is gone now.

If something else looks off to your eyes, let me know :)

2024-07-21 18:26 UTC, schu commented on resources/js/QuestionForm.svelte
> +                <div class="alert alert-light" role="alert">
FIxed, thanks!

2024-07-21 21:55 UTC, levinuss approved these changes
Looks good :) Two things I noticed (but do in my opinion not absolutely need the be changed):
- In the `SessionQuestionView` editor, the selected case for the question is not shown at all (and can therefore also not be changed / edited).
- I think it looks a bit odd, that the cases in the `DeckFormIndex` view are placed in the same list as questions without a visual break (apart from the colors). Could e.g. there be a horizontal line separating questions and cases? I think we could also change this later or keep it this way if you like it.

2024-07-23 19:31 UTC, schu commented
> In the `SessionQuestionView` editor, the selected case for the question is not shown at all (and can therefore also not be changed / edited).

That was an intentional choice, to avoid that users quickly change a case without considering its context (other questions of the same case). But I'm not sure if it's "the better approach", so we might change that later based on experience and user feedback.

> I think it looks a bit odd, that the cases in the DeckFormIndex view are placed in the same list as questions [...]

I agree, changed it to have a separate item list for the cases.

2024-07-24 20:00 UTC, merged