[WIP] Add statistics about answer choices
openmultiplechoice/openmultiplechoice pull request #933
Opened 2024-07-18 19:55 UTC by levinuss

This adds toggleable stats about answer choice frequency by previous users to the SessionAnswerView. The stats are re-calculated every hour for every question that had an answer submitted in the meantime.

Closes #852

2024-07-27 13:42 UTC, schu requested changes

2024-07-27 13:42 UTC, schu commented on resources/js/SessionCardAnswerView.svelte
> +        <p class="mt-2 badge bg-secondary" title="Percentage of users who knew this answer">{answer.answer_percentage}%</p>
If `settingsShowAnswerStats` is enabled but `answer_precentage` hasn't been calcuclated yet for this answers, it would display `null%`. I.e. it's missing a check `answer.answer_percentage != null` as done in SessionAnswerView.

But I don't think there's much value in adding this info to card questions, so I would prefer if we don't calculate/add it for card questions at all. (Also, I think "users who knew this" isn't necessarily true, since it's primarily a flag if the user wants to see the card again or not and not necessarily a reflection of what they actually know..?)

2024-07-27 13:42 UTC, schu commented on app/Models/AnswerChoice.php
> +    public function question()
👍

2024-07-27 13:42 UTC, schu commented on resources/js/UserSettingsView.svelte
> +        <label class="form-check-label" for="flexSwitchCheckDefault">Show statistics about answer choice frequency by previous users</label>
Let's just say `Show answer distribution stats` or something along the lines.

2024-07-27 13:42 UTC, schu commented on app/Console/Kernel.php
> +            $answer_choices = AnswerChoice::select('id', 'question_id', 'answer_id')
Hmm, that's a pretty complex query and hard to parse and understand.

Can we simplify it by having two queries, depending on if we have a previous ID or not? Why not take 10 in both cases?

Nit: variable name should be camelCase.

2024-07-27 13:42 UTC, schu commented on app/Console/Kernel.php
> +            $idLastCalculatedAnswerChoice = Cache::get('internal/last_answer_percentage_calculation');
Nit: I would prefer a shorter variable name, for example `lastAnswerChoiceID`. Since everything happens in the scope of a few line of code, the context should be clear nonetheless.

2024-07-27 13:42 UTC, schu commented on app/Console/Kernel.php
> +                    if (round($totalPercentage) == 100) {
Should this be `!= 100` instead?

2024-07-27 13:42 UTC, schu commented on app/Console/Kernel.php
> +                if ($idLastCalculatedAnswerChoice < $answer_choice->id) {
Can we take `anwer_choices` in ascending order and avoid the check?

2024-07-28 17:32 UTC, levinuss commented on app/Console/Kernel.php
> +            $answer_choices = AnswerChoice::select('id', 'question_id', 'answer_id')
I agree for the two queries.
The 100 in case there is no id in the cache is because I wanted to include the last 100 answer choices in the new queue (but still only process the oldest 10 of them this time). This way, the last 100 answer choices will be processed in the next runs of the scheduler. But the value can definitely be discussed.

2024-09-01 17:15 UTC, levinuss commented on resources/js/SessionCardAnswerView.svelte
> +        <p class="mt-2 badge bg-secondary" title="Percentage of users who knew this answer">{answer.answer_percentage}%</p>
I removed the stats for card questions.

2024-09-04 20:32 UTC, merged

2024-09-04 20:33 UTC, schu commented
Thanks!